name: Metrics Embed - Base

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  examples:
    runs-on: ubuntu-latest

    steps:

      - name: 🗃️ Base content - Default metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Base"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 📗 Classic template - Example
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Base"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 🧱 Core - Large display
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.large.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Base"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 🗂️ GitHub projects - Project from a repository
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.plugin.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: Tomgxz/projects/2
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Base"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: ⏰ WakaTime - WakaTime
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Base"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
