name: Metrics Embed - Calendar

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  examples:
    runs-on: ubuntu-latest

    steps:

      - name: 📅 Isometric commit calendar - Full-year calendar
        uses: lowlighter/metrics@master
        with:
          filename: metrics.calendar.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Calendar"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 📆 Commit calendar - Full history calendar
        uses: lowlighter/metrics@master
        with:
          filename: metrics.calendar.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Workflow: update Metrics Embed - Calendar"
          delay: 120
          user: Tomgxz
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
