name: Metrics Embed - Music

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  examples:
    runs-on: ubuntu-latest

    steps:

      - name: 🎼 Music activity and suggestions - Spotify - Random track from playlist
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.spotify.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/3nfA87oeJw4LFVcUDjRcqi
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 🎼 Music activity and suggestions - Spotify - Recently listed
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 🎼 Music activity and suggestions - Spotify - Top tracks
        uses: lowlighter/metrics@master
        with:
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}

      - name: 🎼 Music activity and suggestions - Spotify - Top artists
        uses: lowlighter/metrics@master
        with:
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
